---
abstract: 'permute multiple-valued key-value pairs'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.100960'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Permute-Named
provides:
  Permute::Named:
    file: lib/Permute/Named.pm
    version: 1.100980
recommends: {}
requires:
  Exporter: 0
  Storable: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Permute-Named
  homepage: http://search.cpan.org/dist/Permute-Named/
  repository: origin
version: 1.100980
